# Generated by Django 6.1 on 2026-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
