# Generated by Django 5.0 on 2026-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
    ]
