# Generated by Django 5.0 on 2026-09-27 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_achievement_starred_by_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='starred_by',
        ),
        migrations.AddField(
            model_name='achievement',
            name='flamed_by',
            field=models.ManyToManyField(blank=True, related_name='flamed_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
