# Generated by Django 5.0 on 2026-09-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_achievement_starred_by_achievement_flamed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
